### ISSUE TITLE
Allow detecting DEPS with the schema // DEPS

### ISSUE THREAD

**Issue by jabrena** [jbangdev/jbang#1194]
Hi,

currently Jbang import dependencies with the syntax:

```
//DEPS
```

but if you code is reformatted by `Google Java Format`, the process add an extra space:

```
// DEPS
```

Is it possible to increase the flexibility in the parser to recognise the space between `//` and `DEPS`

Repo example to observe the behaviour:
https://github.com/jabrena/daily-epsilon

Many thanks in advance

Juan Antonio

**Comment by quintesse** [comment]
@maxandersen I understand why the current format is how it is, I assume mostly to prevent accidental matches in existing comments. But perhaps this is a discussion worth having? Because one might wonder how likely it is to have accidental matches? Most of the code will be written specifically for Jbang anyway, so this would only affect code that a) you didn't write yourself b) works as-is without any changes and finally c) just happens to have a `// XXX` comment that matches one of Jbang's tags.

**Comment by maxandersen** [comment]
I understand the sentiment - I do also think any formatting that adds a space in between characters where there is none is wrong ...but given that - if someone makes a PR that allows detecting using "^//[ \t]*DEPS" (since I assume even tabs could show up? and all existing test passes then I won't say no :)

**Comment by jabrena** [comment]
I was reviewing multiple Java code formatters:
https://github.com/jabrena/java-code-formatter-review-2022

And prettier-java doesn’t offer this problem and in general, offer better results and it is compatible with jbang with the current implementation.

many thanks for the conversation 

Juan Antonio

**Comment by maxandersen** [comment]
Thanks for checking. Glad to see there are sensible formatters :)
