### ISSUE TITLE
add `jbang jdk install 17 <path>`

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1248]
to enable using `jbang jdk install 17  ~/.sdkman/candidates/java/17-open/` to reuse existing sdkman (or any other systems java)

**Comment by maxandersen** [comment]
more specifically to do:

    jbang jdk install 17 `sdk home java 11.0.9.hs-adpt`

**Comment by quintesse** [comment]
Should be doable 🤔

**Comment by nandorholozsnyak** [comment]
I started to work on it, but I see a few problems with this approach, although I like it.

The first approach is easy `jbang jdk install 17 ~/.sdkman/candidates/java/17-open/` - the codes checks if the input parameter is a folder and validates the specific java version using the `release` file, after that a soft link will be created to that folder, I think it is a valid solution.

BTW, I think this code part is "broken", but I may not get something with that: `dev.jbang.util.JavaUtil#parseJavaOutput`
```
public static int parseJavaOutput(String output) {
		if (output != null) {
			Matcher m = javaVersionPattern.matcher(output);
			if (m.find() && m.groupCount() == 2) {
				return parseJavaVersion(m.group(1));
			}
		}
		return 0;
	}
```
The if should be `m.find() && m.groupCount() == 1`, for me it is constantly returning 0 for these inputs `JAVA_VERSION="11.0.14"`. After the change it will return 11. - And the `dev.jbang.util.JavaUtil#determineJavaVersion(java.nio.file.Path)` only works because it has a fallback with the System.getProperty. 

The second approach could work as well, I will try to implement it ASAP, but my only question is the expression will be executed before JBang starts or should JBang resolve it?

**Comment by nandorholozsnyak** [comment]
It does resolve the expression so now it is easier :)

**Comment by nandorholozsnyak** [comment]
Just opened a PR for it: https://github.com/jbangdev/jbang/pull/1252
Tests are missing, will be making them soon.
