### ISSUE TITLE
Dependencies are not on the jshell classpath when starting in interactive mode

### ISSUE THREAD

**Issue by andreaTP** [jbangdev/jbang#1341]
**Describe the bug**

Starting jbang with additional dependencies and in interactive mode should make them available on the classpath.

**To Reproduce**

`jbang --fresh --deps="io.fabric8:kubernetes-client:5.12.2" --insecure --interactive`

I expect to have the fabric8 kubernetes client on the classpath but:

```
[jbang] Resolving dependencies...
[jbang] io.fabric8:kubernetes-client:jar:5.12.2
Done
[jbang] Dependencies resolved
|  Welcome to JShell -- Version 11.0.13
|  For an introduction type: /help intro

jshell> import io.*
|  Error:
|  package io does not exist
|  import io.*;
|  ^
```

**Expected behavior**
the kubernetes-client classes should be available in the jshell session

**JBang version**
`0.92.2`

**Comment by quintesse** [comment]
Hi @andreaTP , the import you're trying to do isn't possible in JShell, try to do the same with `java.`, which obviously exists and you get the same error:

```
jshell> import java.*
|  Error:
|  package java does not exist
|  import java.*;
|  ^
```

I don't know the exact reasoning, but it seems it must be a package that actually directly contains classes.

Also, dependencies are definitely added to the classpath and you can use them:

```
jbang --deps="com.github.lalyos:jfiglet:0.0.8" --interactive
|  Welcome to JShell -- Version 13.0.2
|  For an introduction type: /help intro

jshell> import com.*
import com.*
|  Error:
|  package com does not exist
|  import com.*;
|  ^

jshell> import com.github.lalyos.jfiglet.*
import com.github.lalyos.jfiglet.*

jshell>
```

**But** for some reason it does indeed _not_ work with the kubernetes-client.

I haven't figured out why yet, because the JShell invocation (that you can see when using `--verbose`) seems okay.

**Comment by quintesse** [comment]
Ok, I simply wasn't using the correct import (not knowing anything about the kubernetes-client artifact). But this works:

```
$ jbang --deps="io.fabric8:kubernetes-client:5.12.2" --interactive
jshell> import io.fabric8.kubernetes.client.*

jshell> /import
|    import java.math.*
|    import java.nio.file.*
|    import java.util.concurrent.*
|    import java.util.function.*
|    import java.util.prefs.*
|    import java.util.regex.*
|    import java.util.stream.*
|    import java.lang.*
|    import java.util.*
|    import java.io.*
|    import java.net.*
|    import java.math.BigInteger
|    import java.math.BigDecimal
|    import io.fabric8.kubernetes.client.*

jshell>
```

Things works as expected. Closing this issue. You can always reopen if there's something I've missed.

**Comment by quintesse** [comment]
Great! Glad I could be of assistance!

Btw, you probably don't need `--fresh`, it will slow things down quite a bit because it will re-do a bunch of work each time. I'd reserve it for those moments you're accessing a remote resource you know has been updated or when things don't seem to update correctly/stay cached.
