### ISSUE TITLE
jshell fails under windows due to no support for @file

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1349]
"jbang -s symjajsh@axkr -i --verbose" results in massive argset which results in @file being generated which then fails with 

```
C:\jbang-0.92.2\bin>jbang symjajsh@axkr
File '@C:\Users\dev\AppData\Local\Temp\jbang8080717266275010342.args' for 'jshell' is not found.
```

reading https://docs.oracle.com/en/java/javase/13/docs/specs/man/jshell.html I don't see any @file support - maybe we'll have to have it load classpath via env variable or load in generated script instead?

discovered in https://github.com/axkr/jbang-catalog/pull/1

**Comment by maxandersen** [comment]
running the full jshell command does work in powershell - are we too agressive in generating those @file ?

**Comment by quintesse** [comment]
> via env variable

ENV vars have limits on Windows too

> load in generated script instead?

AFAIK that won't help, it's the parser that has the limit, and that's the same on the command line as in a bat/cmd file.

> are we too aggressive in generating those `@file`?

Very likely, there's no good documentation on what the actual limits are.
But then the user would have to be using Powershell (and not accidentally starting jbang using the .cmd script, but that should not happen normally, except if they type `jbang.cmd` explicitely) and it would still only move the problem somewhat further because even PowerShell has limits to the max command length. (I think it's 32KB).

**Comment by maxandersen** [comment]
By script I mean the jsh we pass to jshell. We should be able to set classpath here.  But not sure we can set both so completion works as well as execration ?

**Comment by quintesse** [comment]
> By script I mean the jsh we pass to jshell

Yes, that's what how I understood, but how are you going to set the classpath using script?

**Comment by maxandersen** [comment]
"/env -class-path /opt/libs/commons-lang3-3.4.jar:/opt/libs/guava-19.0.jar"

**Comment by quintesse** [comment]
Aha! No idea that existed 👍
