### ISSUE TITLE
Show full integration errors when verbose mode is active

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#1499]
See https://github.com/jbangdev/jbang/issues/1475#issuecomment-1270411190

**Comment by maxandersen** [comment]
so I think not only are we hiding the exceptio but we are also not actually capturing error output. So can't actually see the true error anymore.

**Comment by filippor** [comment]
Yes the output is used to get the result. Maybe it is possible to use the error stream for errors

**Comment by maxandersen** [comment]
this keeps biting me. it works when running internally. when external launch we don't capture error and no error reported.

i.e. have a broken pom.xml (syntax error) next to a main.java depending on quarkus and it will fail with no info if running with java8 but it has //JAVA 17+ ...and the root cause is that quarkus can't parse the pom.xml (which it shouldn't do but we should at least report why its failing)

**Comment by quintesse** [comment]
The reason this was never really implemented is because it's hard to determine what the error is. The integration code is completely free to write whatever it likes to stdout and stderr, so how do we pass an error back to the main process?

We could perhaps force any output to go to stdout only and use stderr for any errors, but that would mean the output might change depending on how the integration is run. That doesn't sound acceptable.

We could of course write the error to some known file but i really think that's a crappy solution. Can anybody come up with a better solution?

**Comment by quintesse** [comment]
Well, now that I think of it the external proces could simply write the error to stderr (if --verbose is set). That way the main process still isn't any the wiser but at least the user gets their error message.

**Comment by maxandersen** [comment]
Yeah. I would Think we just need to relay steder to stderr and stdout to stdout and just treat it like we do internal integration run.
