### ISSUE TITLE
Make Jbang use default JDK by default?

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#1537]
The title might seem weird, but right now Jbang will actually prefer to use any JDK found on the PATH or in JAVA_HOME than what was set using `jbang jdk default`. 

Now, by default we add the "default" JDK to the user's PATH in their bashrc/zshrc/etc if they run `jbang app setup`, but that's not a requirement for using Jbang, so perhaps the user never did that.

So I'm suggesting that Jbang (both the main code and the startup scripts) use whatever the default JDK is set to over what is available on the PATH or whatever JAVA_HOME points to.

This basically would come down to using a provider order of: `default , path , javahome , jbang`.

WDYT? Is there any reason not to do this?

**Comment by quintesse** [comment]
Just going to add a counter-argument myself: a user might say "Hey, my default JDK is managed by me, so why isn't Jbang using it? If I'd want to use Jbang's default JDK I'd add it to my PATH, so I like the current behaviour just fine!"

**Comment by maxandersen** [comment]
Correct. Thats why i did it that dag originally. Jbang is trying to honor what is the users own default managed setup rather than creating its own parallel Universe. Especially trying to avoid jbang installing a jdk when one already svailable which would be the consequence to have jbang honor its own default first. 

Thus -1 to make jbangs default the default.

**Comment by quintesse** [comment]
Perfect. Closing then.
