### ISSUE TITLE
-Dkey=value parsing on windows is broken in jbang.cmd

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#157]
Given keyvalue.java:

```
import java.util.Arrays;

public class keyvalue {

    public static void main(String[] args) {
        Arrays.stream(args).forEach(System.out::println);
    }
}
```

`java keyvalue.java -Dxyx=123` prints `-Dxyx=123`

`jbang keyvalue.java -Dxyx=123` prints 

```
-Dxyx
=123
```

same thing gets applied to `jbang -Dxyx=123` thust cant set system properties on java

**Comment by quintesse** [comment]
Unable to reproduce this with JBang 0.31.0 on Windows....

**Comment by quintesse** [comment]
Reproduced in 0.32.0

**Comment by quintesse** [comment]
This was an existing problem. Changing the `jbang.cmd` like this shows the problem:

```
echo %*
FOR /F "tokens=*" %%a in ('%JAVA_EXEC% %JBANG_JAVA_OPTIONS% -classpath %jarPath% dk.xam.jbang.Main %*') do SET OUTPUT=%%a
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%
echo %OUTPUT%
```

Given `-Dabc=def` it outputs:

```
https://github.com/quintesse/jbang-scripts/blob/master/echo.java -Dabc=def
C:\Users\tako\scoop\apps\openjdk\current\bin\java.exe -classpath ;C:\Users\tako\.jbang\cache\jars\echo.java.dc1725c55f5e83c1c355faf3ac049d5f2982336581e81e678ab39396fd562448.jar echo -Dabc def
```

So the problem is caused by the `FOR`.

I think we should get rid of that. If you really want to maintain the globbing feature for Windows I think we should just move that to JBang itself and do the expansion there. We can be much smarter about it in that case.

**Comment by maxandersen** [comment]
the FOR /F's main purpose is to avoid piping to a file - but yeah, afaics FOR /F affects how arguments are passed in and it also swallows exit code which messes up other things.

Now - how does one safely generate a random temporary file on windows you are guaranteed to be able to write to (probably somtehing in JBANG_DIR) is the challenge + remove/clean it up again.

**Comment by quintesse** [comment]
I'm not sure I understand, what's the reason for creating a temporary file? (and is that what it's doing? I thought the only thing it did was expand the glob tokens and loop over its arguments.)

**Comment by maxandersen** [comment]
the thing jbang jar is basically to output a java command wich the shell script or batch script dependent on platform executes.

In linux/shell scripts we can just pipe/collect error codes easily.

In windows there is no way (that I know off) where you can store the result of executin in a variable without either using a temporary file for storage OR use FOR /F

I think I have suggested fix for it in #158

**Comment by quintesse** [comment]
> In windows there is no way (that I know off) where you can store the result of executin in a variable without either using a temporary file for storage OR use FOR /F

Aha! Didn't know that.

What you suggest should probably work. But another solution might be (if in the end it turns out not to work or if we encounter even worse problems in the future) to just use a PowerShell script (`*.ps1`). Powershell is supposedly already available by default since Windows 7.

**Comment by maxandersen** [comment]
i now got all windows tests passing in #158 using `.cmd` - hopefully never have to touch that again :)

**Comment by maxandersen** [comment]
closing this as fixed with latest updates.

p.s. powershell might be better future solution but won't come from me at the moment :) PR's welcome - should be "easy" now as test suite there to know when you messed up (or not :)

**Comment by quintesse** [comment]
Luckily it's one of those things that when it work you probably never have to touch it again. It's knowing that it work that's the problem heheh

Btw, I think JBang also needs to support @commandFiles , like Java does. Otherwise we'll run into the problem of the limited command line size on Windows. I'll open an issue for that (#161).
