### ISSUE TITLE
enable preview should be more consistently available

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1622]
trying out java 21 with jshell turns out harder than wanted:

```
JBANG_JDK_VENDOR=openjdk jbang --java 21 -i -R --enable-preview -C --enable-preview
jshell> STR."test"
|  Error:
|  string templates are a preview feature and are disabled by default.
|    (use --enable-preview to enable string templates)
|  STR."test"
|      ^
```

this fails as `--enable-preview` is not passed to jshell.

Given `--enable-preview` now is a common flag; should we have that as a first-class thing that will consistently enable-preview across jshell, javac, java ?

**Comment by quintesse** [comment]
> this fails as --enable-preview is not passed to jshell.

Well, generically speaking it is passed to jshell, but as a flag that has to be passed further down the compiler/runtime chain, the thing we do with all runtime flags. Thing is that doesn't actually affect jshell's behaviour, probably because it has its own (pre-)parse stage or something. Anyway, jshell has its own --enable-preview flag.

So I agree it seems like a good idea to have our own specific flag for enabling this feature both for running .java or .jsh files and making sure we enable it in the correct way for each situation.

A minor issue might be that we already have a `--preview` flag of our own, so having an `--enable-preview` as well might be confusing.

**Comment by maxandersen** [comment]
Yes. A potential confusion exist but I would say --enable-preview would be the flag we want to have consistent jvm flags.

But not sure I would go as far to say --enable-preview and --preview should merge. Think okey to keep them separate as is now.

**Comment by quintesse** [comment]
I would indeed not merge the two. Still, having two similarly named options seems weird to me. Aren't there perhaps different names we could come up with? `--jdk-preview` or something?

**Comment by quintesse** [comment]
That might be a nice option, yes
