### ISSUE TITLE
support generating classpaths embedded on command line

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1703]
I find that sometimes cli's out there need a classpath and it can be quite tedious to type out.

I wonder if like done in #1043 where %{url} fetches content and make it available as a file we could support %{deps://DEPS syntax} to generate classpath.

i.e.

`jbang sqlline@maxandersen -cp %{deps:org.hsqldb:hsqldb:RELEASE,..} other args`

**Comment by maxandersen** [comment]
@quintesse tell me if i'm crazy or we should just do this :)

**Comment by quintesse** [comment]
It doesn't seem totally crazy, no.
But do we have a clear use-case where this enables something we can't do in another way?

Because I don't think you're interested in passing in the classpath as an argument to a script, right? (Which is what `%{url}` was meant for)

**Comment by maxandersen** [comment]
My usecase is https://github.com/jupyter-java/jbang-catalog/blob/main/installkernel.java where some of kernels especially the kotlin one expects a seperate classpath list as argument. 

Similar to the sql drive tooling above. 

Reason for deps: prefix is that we allow https urls to GitHub repo as deps too which would need treating differently i think?

**Comment by quintesse** [comment]
> Reason for deps: prefix is that we allow https urls to GitHub repo as deps too which would need treating differently i think?

You're probably right. I don't think it would be impossible to come up with a scheme where we wouldn't have to use the prefix, but it might mean that we'd have to choose one interpretation over another.

Still, I like the simplicity of `%{org.hsqldb:hsqldb:RELEASE}`. Perhaps we can make the prefix(es) optional where they work to force one interpretation over another when the contents is ambiguous? Eg: `%{org.hsqldb:hsqldb:RELEASE}` would be ok, because it's obviously not an URL. The same with `%{http://www.google.com}`. But the issue would be `%{https://github.com/jbangdev/jbang}`.

In that case we can add the option to add a prefix: `url` or `dep`. I think it's good to have both for consistency.

And then we can use:

`%{url:https://github.com/jbangdev/jbang}`

and

`%{dep:https://github.com/jbangdev/jbang}`

(Btw, using "dep" here for the examples, but we can do "deps" too of course.)
