### ISSUE TITLE
jbang cache clear should allow controlling which parts gets nuked

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#191]
like:

`jbang cache clear` is the big default nuke (implicitly set --all to true)
`jbang cache clear --url --jdk` nukes only url and jdk cache
`jbang cache clear --all --no-jdk`  nukes everything but jdk.

**Comment by quintesse** [comment]
Ha! Exactly what I was about to propose :-)

Although I'd suggest a couple of things to make life easier:

 - make the default --url --jar
 - don't do -no-xxx

Because default (being --all) is easiest to use but you almost never want to nuke the JDKs, the default should be what most people need. Don't make that case harder. And once you have that the -no-xxx options become unnecessary IMO.
