### ISSUE TITLE
JBang downloads JDK again

### ISSUE THREAD

**Issue by tivrfoa** [jbangdev/jbang#471]
Hi!

I did a test using `//JAVA 15` and it downloaded the correct version, nice.

After a while when I ran the test again, it downloaded again :cry: 

I'm almost sure that I didn't deleted `.jbang/cache/jdks`

So my suggestion is to place jdk maybe at the same level as `cache` folder.
Once downloaded it should stay there till the end of times.
It's really bad for people that have a slow connection like me.

**Comment by quintesse** [comment]
That certainly possible. The reason that your cache gets deleted is most likely because you've compiled Jbang from sources. There is some unfortunate code in the tests that delete the entire cache folder. So the other option is to get rid of that code, runing tests shouldn't affect a user's system IMO.

**Comment by tivrfoa** [comment]
Thanks @quintesse 

Well if doesn't affect end users, then it's not really an issue.
JBang developers can get around that.

What I am doing is setting my $JAVA_HOME to the same version as `//JAVA` then it doesn't trigger the download. :)
I'm going to close it.

**Comment by maxandersen** [comment]
we probably should get our testsuite to isolate itself from the default install. We have all the env settings available for it it.
