### ISSUE TITLE
Support bi-directional file watch between source dir and temp dir

### ISSUE THREAD

**Issue by murphye** [jbangdev/jbang#612]
# Scenario

1) Assume that I hava a Git repo with a `todo.java` and a `README.md`.
2) I run 
```
code `jbang edit todo.java`
```
3) In VS Code, I make changes to my `README.md`
4) In VS Code, I create a `todo.properties`

# Result

1) `README.md` is not refreshed in my Git project, even when I do `jbang edit --live`
2) `todo.properties` is not refreshed and added back to my Git project

Ultimately, this results in a broken IDE experience, as only the `todo.java` is watched and refreshed in my Git project during edit. It is also confusing to a developer, because when they check their Git project status, there are no recorded changes to the files.

# Proposed Solution
1) Offer an option to watch and refresh the original directory when doing `jbang edit` with all source files, including `.md` and `.properties`
2) This would provide a fully functioning development experience on a project level, and not just for a `.java`

**Comment by murphye** [comment]
I guess you could say that it would be watching in a bi-directional manner. Both the source directory and the temp directory.

**Comment by maxandersen** [comment]
I think this would be too flakey to be honest.

But I recognize the issue and was thinking "fixing" this by doing #462 where instead of using temporary dir approach generate ide files into where it comes from. This has limits too (like having to locate `src` dir and put IDE files in the dir above that) but I think that at least for now that is simpler than starting to do two-way syncs of the files and dirs.

**Comment by murphye** [comment]
Yes, https://github.com/jbangdev/jbang/issues/462 is a good approach, if possible to achieve.

**Comment by maxandersen** [comment]
closing as solution is more likely to be #462
