### ISSUE TITLE
move from "unleash the power of java for shell scripting" to "unleash the power of java" in docs/readme's

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#625]
with jbang's ability to now run, package and install (almost) any jar (not just scripts) the current tag line is rather limiting. 

making this issue to keep reminding to get it updated in all the various install/readme's for the various setup tools

- [ ] jbang-action
- [ ] copr
- [ ] choco
- [ ] ...?

**Comment by karstentorp** [comment]
I have cloned all 16 repos and searched for "for shell scripting" and only got 3 hits.

There are two problematic files where the text need to be changes 1 place in each: `jbang.dev/index.html` and `jbang.dev/_config.yml`.

`jbang\readme.adoc` have a reference to a talk that IMO is ok because it is the name of a talk Max gave at DevNation.

Searching for just "scripting" yields 12 hits, but they are all par part of some larger text that seams ok or a tag list. eg.: `jbang\src\main\scripts\choco\jbang.nuspec` has this in <tags>jbang bash java shell scripting</tags>. This is ok because its just tags and not a sentence.

**Comment by karstentorp** [comment]
I have fixed `jbang.dev/index.html` and `jbang.dev/_config.yml` and created a PR.

**Comment by maxandersen** [comment]
already done!
