### ISSUE TITLE
jbang app install thinks jbang is already installed

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#827]
```
curl -Ls https://sh.jbang.dev | bash -s - app install jbang
[jbang] jbang is already available, re-run with --force to install anyway.
```

this is with no jbang in path, no .jbang folder and nothing in bashrc.

using --force works but shouldn't be required...

**Comment by quintesse** [comment]
yeah, this is basically because the moment `jbang` is able to run it's already installed. Doing `curl xxx | bash -s anything` is basically the same as doing `jbang app install jbang`. There's no way to tell the difference. That's why it's better to tell people to use `curl xxx | bash -s app setup` not `app install jbang`.

I've thought about it before but I don't know how to improve this.,

**Comment by quintesse** [comment]
So just to make it doubly clear: `curl xxx | bash -s app install jbang` is basically the same as running `jbang app install jbang` twice. So the startup script will, when no jbang is currently installed, perform the exact same steps as running `jbang app install jbang` does. which is why running `curl xxx | bash -s app install jbang` makes no sense.

**Comment by maxandersen** [comment]
But what command do we otherwise document as installing jbang...As jbang isn't actually installed ie. It's not in path.

**Comment by quintesse** [comment]
> That's why it's better to tell people to use curl xxx | bash -s app setup not ... app install jbang.

☝️

**Comment by quintesse** [comment]
Which btw is already what we tell people in our docs: https://github.com/jbangdev/jbang#using-jbang

**Comment by maxandersen** [comment]
Gah, of course!

Note to myself: don't update website docs around midnight

**Comment by maxandersen** [comment]
fixed https://www.jbang.dev/download
